### ISSUE TITLE
Phpunit failing

### ISSUE THREAD

**Issue by stafot** [laravel/browser-kit-testing#101]
- Browser Kit Testing Version:5.1.2
- Laravel/Lumen Version: 5.8 
- PHP Version: 7.3.2
- PHPUnit Version: Either 7.5.13 or 8.x

### Description:

Failing to run tests getting the following error.
`Error: Call to undefined method App\Console\Kernel::bootstrap()`

Based on [this](https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0) and README of this repo. I created a trait `CreatesApplication.php` and call it from the `BrowserKitTestCase.php`. 
Same results having even if instead of having trait I have a `createApplication` function on `BrowserKitTestCase.php`.

### Steps To Reproduce:
Run phpunit

**Comment by driesvints** [comment]
Are you using Laravel or Lumen? We don't support integration with Lumen.

**Comment by stafot** [comment]
Sorry I assumed you support both. So for lumen the only option is to move to dusk?

**Comment by driesvints** [comment]
@stafot if you want to use Dusk it's best that you migrate the app to Laravel.
