### ISSUE TITLE
无法调用ChoiceFormField类的disableValidation方法

### ISSUE THREAD

**Issue by Jackyilee** [laravel/browser-kit-testing#109]
请问一个问题，我在使用laravel/browser-kit-testing包做浏览器管理端测试的时候，使用的是laravel-admin搭建的临时后台。
   我在测试select单选框的时候使用的是ajax异步加载的方式，而options备选框的返回为空（为了节省内存）,此时我传对应表单进行测试验证的时候，出现了“您所提交的值不在备选框内“”的错误提示，因此我需要关闭表单验证。
  由于创建ChoiceFormField类的对象需要找到当前表单的DOMElement对象，才能够得到当前页面的测试对象。我想问一下我怎么拿到当前页面的DOMElement然后执行disableValidation方法关闭表单验证，非常感谢！

**Comment by driesvints** [comment]
I'm very sorry but we can only provide support in English. Maybe try https://learnku.com/laravel ?
