### ISSUE TITLE
Use of assertIsArray in seeJsonStructure requires phpunit >= 7.5

### ISSUE THREAD

**Issue by katjam** [laravel/browser-kit-testing#120]
- Browser Kit Testing Version: 4.2.0
- Laravel Version: 5.7
- PHP Version: 7.2
- Phpunit version 7.0.3

### Description:
I haven't taken the time to dive too far into this but hope this can help others with my issue.

The issue is with compatibility with phpunit 7.*

The phpunit assertion `assertIsArray` is not added until phpunit 7.5

### Steps To Reproduce:
Use assertion `seeJsonStructure` with wildcard `*`with library versions as above.

### Solution:
- User can: Downgrade browser-kit-testing to <=4.1 or upgrade phpunit to >=7.5
- browser-kit-tresting >4.1 can: require phpunit >=7.5

**Comment by driesvints** [comment]
You're correct. I'll bump the dependencies. Thanks for reporting this.

**Comment by driesvints** [comment]
Will be in tomorrow's release.
