### ISSUE TITLE
Use illuminate/testing

### ISSUE THREAD

**Issue by crynobone** [laravel/browser-kit-testing#122]
In particular `Illuminate\Testing\TestResponse`.

Based on my review it would be possible to use `TestResponse` with browser-kit-testing but the are some differences that we need to manage:

* `assertResponseOk` is same as `TestResponse::assertOk()`
* `assertResponseStatus` is same as `TestResponse::assertStatus()`
* `assertRedirectedTo` is similar to `TestResponse::assertRedirect()`
* `dump()` return void but `TestResponse::dump()` return $this.

There no equivalent to:

* `assertRedirectedToRoute`
* `assertRedirectedToAction`

**Comment by driesvints** [comment]
We can definitely look at this. Feel free to send in a PR if you want.
