### ISSUE TITLE
Not compatible with PHPUnit 6

### ISSUE THREAD

**Issue by Anahkiasen** [laravel/browser-kit-testing#13]
The package uses PHPUnit classes but does not list it as a dependency. That means you can install it alongside PHPUnit 6 while in reality it will crash. I think `"phpunit/phpunit": "<=6.0"` (or something) should be added as dependency of this package

**Comment by hohl** [comment]
Any ideas why it fails? Would it be hard to fix that and support PHPUnit 6 too?

**Comment by valorin** [comment]
A really sneaky cheat for this is to add this into your `app.aliases` config list:

```
'PHPUnit_Framework_Assert' => \PHPUnit\Framework\Assert::class,
```

**Comment by kamui545** [comment]
For some reasons it looks like adding those aliases in `config/app.php` does not work (at least on my setup)

What I did is adding in `tests/BrowserKitTestCase.php` the following code (you may need to add more aliases, depending on your tests):

```
class_alias(\PHPUnit\Framework\TestCase::class, 'PHPUnit_Framework_TestCase');
class_alias(\PHPUnit\Framework\Assert::class, 'PHPUnit_Framework_Assert');
class_alias(\PHPUnit\Framework\Constraint\Constraint::class, 'PHPUnit_Framework_Constraint');
```

**Comment by tms320c** [comment]
I use PHPUnit 5.7 and I got laravel/browser-kit-testing version 2.0.0, which does not work with PHPUnit 5
Thanks to @kamui545 it can be fixed in the same but mirrored way: add to tests/BrowserKitTestCase.php the following code:

`class_alias('PHPUnit_Framework_TestCase', \PHPUnit\Framework\TestCase::class);`
`class_alias( 'PHPUnit_Framework_Assert',\PHPUnit\Framework\Assert::class);`
`class_alias('PHPUnit_Framework_Constraint', \PHPUnit\Framework\Constraint\Constraint::class);`

**Comment by redgluten** [comment]
Same situation as @tms320c : laravel 5.4.27, browser-kit-testing 2.0.0 and phpunit 5.7.20. I followed the [Upgrade guide instructions](https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0) to keep my existing tests and I got a `Fatal error: Class 'PHPUnit\Framework\Constraint\Constraint' not found`. Using the class aliases fixed the problem.

**Comment by kamui545** [comment]
It's simple.

If you are using PHPUnit 5.x, use browser-kit-testing 1.x
If you are using PHPunit 6.x, use browser-kit-testing 2.x

**Comment by redgluten** [comment]
Ah you’re right, so there’s an issue with the upgrade guide with the command for requiring `browser-kit-testing`: `composer require laravel/browser-kit-testing --dev` gets 2.0 despite the guide recommending to use phpunit ~5.7. I’ll submit a PR.

**Comment by ajcastro** [comment]
What is the recommended browserkit and phpunit to use?

**Comment by ajcastro** [comment]
@redgluten , what guide do you refer? Can you please provide the link. Thanks!

**Comment by phpguru** [comment]
For Laravel 5.4, I found that my global phpunit > 6 was too new, and just running `$ phpunit path/to/test.php` was breaking with this error. I had `"phpunit/phpunit": "^6.0.3",`
 in composer.json. After reading this and other similar issues around the web, the problem went away after downgrading PHP unit and using `"phpunit/phpunit": "~5.7",` in composer.json, composer update, and then using the project-specific phpunit `$ vendor/bin/phpunit path/to/test.php`.

**Comment by driesvints** [comment]
Library now requires a minimum of PHPUnit 7.0
