### ISSUE TITLE
Extending from Laravel\BrowserKitTesting\TestCase lose assertions that I already know/have

### ISSUE THREAD

**Issue by brainlet-ali** [laravel/browser-kit-testing#133]
When I install and use this package, I no longer have access to assertions like:
- assertStatus
- assertOK

And rather I'm forced to use assertResponseStatus which doesn't feel natural and asking me the leave the testing API that I already know.

**Comment by driesvints** [comment]
Think you're confusing Browser Kit Testing with the regular TestCase class of Laravel. They're two different things.
