### ISSUE TITLE
Multiple Forms with same name tag

### ISSUE THREAD

**Issue by justustheis** [laravel/browser-kit-testing#134]
Hello there :)

I am trying to test a page with multiple forms. All the forms use the same field names (editing multiple users at once). My understanding is, that the methods for form testing require the field name. But in my case these are not unique. Is there a way to use the field id instead?

Thanks!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
