### ISSUE TITLE
Outdated MocksApplicationServices.php implementation

### ISSUE THREAD

**Issue by bytestream** [laravel/browser-kit-testing#141]
Comparison of:
* https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php
* https://github.com/laravel/browser-kit-testing/blob/6.x/src/Concerns/MocksApplicationServices.php

`withoutEvents()` diff:
```php
$mock = Mockery::mock('Illuminate\Contracts\Events\Dispatcher');

$mock->shouldReceive('fire', 'dispatch', 'getCommandHandler')->andReturnUsing(function ($called) {
    $this->firedEvents[] = $called;
});

$this->app->instance('events', $mock);

return $this;
```

```php
$mock = Mockery::mock(EventsDispatcherContract::class)->shouldIgnoreMissing();

$mock->shouldReceive('dispatch', 'until')->andReturnUsing(function ($called) {
    $this->firedEvents[] = $called;
});

Event::clearResolvedInstances();

$this->app->instance('events', $mock);

return $this;
```

I noticed this having tried to use `expectsEvents()` and ran into a mockery error stating `until` was called but had not been mocked.

There are other differences https://www.diffchecker.com/HRM1BixO

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.
