### ISSUE TITLE
Outdated MocksApplicationServices.php implementation 

### ISSUE THREAD

**Issue by bytestream** [laravel/browser-kit-testing#142]
- Browser Kit Testing Version: 5.1.4
- Laravel Version: 6.18.38
- PHP Version: n/a - 7.3.21
- Database Driver & Version: n/a

### Description:

Comparison of:

*    https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php
*    https://github.com/laravel/browser-kit-testing/blob/6.x/src/Concerns/MocksApplicationServices.php

`withoutEvents()` diff:

```php
$mock = Mockery::mock('Illuminate\Contracts\Events\Dispatcher');

$mock->shouldReceive('fire', 'dispatch', 'getCommandHandler')->andReturnUsing(function ($called) {
    $this->firedEvents[] = $called;
});

$this->app->instance('events', $mock);

return $this;
```

```php
$mock = Mockery::mock(EventsDispatcherContract::class)->shouldIgnoreMissing();

$mock->shouldReceive('dispatch', 'until')->andReturnUsing(function ($called) {
    $this->firedEvents[] = $called;
});

Event::clearResolvedInstances();

$this->app->instance('events', $mock);

return $this;
```

I noticed this having tried to use `expectsEvents()` and ran into a mockery error stating `until` was called but had not been mocked.

There are other differences https://www.diffchecker.com/HRM1BixO

### Steps To Reproduce:

```php
$this->expectsEvents([Foo::class]);
```

**Comment by driesvints** [comment]
We don't maintain this version anymore. Can you please upgrade to 6.x and try again? Feel free to open a new issue if it persists.

**Comment by bytestream** [comment]
You can see the same issue expects on the `6.x` branch which I accidently linked in my original message:
* https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php#L98
* https://github.com/laravel/browser-kit-testing/blob/6.x/src/Concerns/MocksApplicationServices.php#L97

Unfortunately `6.x` requires Laravel 7 so I cannot upgrade.

---

Given Laravel 6 is LTS until Sept 2021 (https://laravel.com/docs/6.x/releases) I would think this package should also follow that schedule.

**Comment by driesvints** [comment]
@bytestream only the frameworks follows LTS, not its first party libraries. As per our release policy: https://laravel.com/docs/7.x/releases#support-policy

> For all additional libraries, including Lumen, only the latest release receives bug fixes.

**Comment by bytestream** [comment]
> 
> 
> @bytestream only the frameworks follows LTS, not its first party libraries. As per our release policy: https://laravel.com/docs/7.x/releases#support-policy
> 
> > For all additional libraries, including Lumen, only the latest release receives bug fixes.

Ah thanks for the link. I was not aware of that.

> 
> 
> Tbh, I don't immediately understand the problem here. If you can give specific steps to reproduce (also show what Foo is) then I'll try to reproduce it.

Should be replicable with the below:

```php
public function testExpectsEvents()
{
    $this->expectsEvents([
        MessageSending::class,
        MessageSent::class,
    ]);
        
    app('mailer')->raw('foo', function ($message) {
        //
    });
}

/*
Mockery\Exception\BadMethodCallException : Received Mockery_0_Illuminate_Contracts_Events_Dispatcher::until(), but no expectations were specified
/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:508
/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:260
/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:185
*/
```

**Comment by bytestream** [comment]
I am sure there are other outdated function implementations if you compare `laravel/framework` to this package.

**Comment by driesvints** [comment]
@bytestream I think at this point it's best that you attempt a PR to the 6.x branch.
