### ISSUE TITLE
Add documentation about Laravel versions compatibility

### ISSUE THREAD

**Issue by vedmant** [laravel/browser-kit-testing#145]
Hi, I have Laravel 6 and was not able to install laravel/browser-kit-testing according to current docs, it appeared that I had to install specific version ^5 plus there are issues with other dependencies like "symfony/css-selector", this should be in docs.

**Comment by nafiesl** [comment]
Nice idea, @vedmant. This is the solution I found related to this dependency issue https://github.com/laravel/browser-kit-testing/issues/113#issuecomment-569461601.

**Comment by vedmant** [comment]
@nafiesl It actually does't work, I had to specify browser-kit-testing version as well to be able to install on Laravel 6: `composer require laravel/browser-kit-testing:^5.0 --dev`

**Comment by driesvints** [comment]
We don't support Laravel 6 anymore in the latest browser kit version, sorry. We also won't be recommending it in our latest docs to encourage people to upgrade.

**Comment by vedmant** [comment]
Really, why? Laravel 6 us an LTS, it lives longer than both version 7 and
8, there is no next LTS. Laravel have to be supported as the latest LTS
version.

**Comment by driesvints** [comment]
Laravel 6 is LTS but our 1st party libraries aren't. Please see our support policy: https://laravel.com/docs/8.x/releases#support-policy

> For all additional libraries, including Lumen, only the latest release receives bug fixes.
