### ISSUE TITLE
MakesHttpRequest wrong return-value in phpdoc block

### ISSUE THREAD

**Issue by indeyets** [laravel/browser-kit-testing#149]
- Browser Kit Testing Version: 6.2.1
- Laravel Version: 7.29.3
- PHP Version: 7.3

### Description:
[MakesHttpRequests::call()](https://github.com/laravel/browser-kit-testing/blob/6.x/src/Concerns/MakesHttpRequests.php#L558-L560) is annotated to return `\Illuminate\Http\Response`, but it actually returns `Laravel\BrowserKitTesting\TestResponse`.

It leads to warnings from static analysis tools such as [PhpStAn](https://phpstan.org/)

### Steps To Reproduce:

1. check signature of [TestResponse::fromBaseResponse](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Testing/TestResponse.php#L54-L63)
2. compare it to signature of [MakesHttpRequests::call()](https://github.com/laravel/browser-kit-testing/blob/6.x/src/Concerns/MakesHttpRequests.php#L558-L560)

**Comment by driesvints** [comment]
Feel free to PR something
