### ISSUE TITLE
External URL testing purpose

### ISSUE THREAD

**Issue by muhsarip** [laravel/browser-kit-testing#152]
i've working with multiple app that built from some stack, there are laravel, codeigniter and native php. The apps actually support single mobile apps as a core system. late enhancement make me confusing about the bug show everywhere when one feature added. i just tried at laravel unit testing before, it can not use external url as url in json() method. i just want to ask , is this repository can help testing multiple url, such as api response only?

**Comment by crynobone** [comment]
Nope, this test library is meant to be used just within Laravel.

**Comment by muhsarip** [comment]
i see, i should use another trick. thank you
