### ISSUE TITLE
Support for parallel testing

### ISSUE THREAD

**Issue by SkepticalHippo** [laravel/browser-kit-testing#157]
- Browser Kit Testing Version: 6.2.2
- Laravel Version: 8.51.0
- PHP Version: 8
- Database Driver & Version: MySQL 5.7

### Description:

It doesn't look like `browser-kit-testing` has support for the new [parallel testing](https://laravel.com/docs/8.x/testing#running-tests-in-parallel) functionality.

Is it something that would be considered to be added to the library, or should it only be used to support apps that have these legacy tests?

I'd be open to attempting a PR for this.

### Steps To Reproduce:

* Write a test that extends `Laravel\BrowserKitTesting\TestCase`. 
* Run tests using `php artisan test --parallel`.

**Comment by driesvints** [comment]
We have no plans for this sorry.

**Comment by nafiesl** [comment]
Hello @SkepticalHippo what kind of issue did you get when running the parallel test?

This project uses the new parallel test with no issue.
https://github.com/nafiesl/free-pmo
(Check the `.travis.yml` file. But I am using in memory sqlite DB there.)
