### ISSUE TITLE
Assert response is json broken in v6

### ISSUE THREAD

**Issue by bytestream** [laravel/browser-kit-testing#159]
- Browser Kit Testing Version: 6.22
- Laravel Version: 7.30.5
- PHP Version: 7.4.26
- Database Driver & Version:

### Description:

In v6 `seeJson()` is no longer possible and produces:
```
TypeError : Argument 1 passed to Laravel\BrowserKitTesting\TestCase::seeJsonEquals() must be of the type array, null given
```

Broken by https://github.com/laravel/browser-kit-testing/commit/d472e1c8f0d11614106db9c75435bdaf723e3290 which proclaimed:
> This mainly aim to check if response is actually JSON.

This is what the reproducer below also intends to do.

### Steps To Reproduce:

```php
$this->json('GET', route('???'))
            ->seeJson()
            ->assertResponseOk();
```

**Comment by driesvints** [comment]
I'm not sure I understand? Your issue is with `seeJsonEquals` which only accepts an array. How does this affect `seeJson`?

**Comment by bytestream** [comment]
https://github.com/laravel/browser-kit-testing/blob/2dfb9c0fc65ad224d689899506155274fd640cb5/src/Concerns/MakesHttpRequests.php#L418

@driesvints `seeJson()` defaults `$data` to `null` which is passed to `seeJsonEquals`.

**Comment by driesvints** [comment]
Okay I see what you mean. Thanks, we'll check in on that.

**Comment by driesvints** [comment]
Fixed. Will be in tomorrow's release: https://github.com/laravel/browser-kit-testing/pull/160

**Comment by bytestream** [comment]
Great thanks :+1:
