### ISSUE TITLE
ADD Null Safety

### ISSUE THREAD

**Issue by allanlaal** [laravel/browser-kit-testing#170]
add Null safety to whereever appropriate, so things like this wouldn't be fatal:
	
   ErrorException 
	
	  Trying to access array fset on value of type null
	
	  at vendor/laravel/browser-kit-testing/src/Concerns/ImpersonatesUsers.php:32
	     28▕      * @return void
	     29▕      */
	     30▕     public function be(UserContract $user, $driver = null)
	     31▕     {
	  ➜  32▕         $this->app['auth']->guard($driver)->setUser($user);
	     33▕     }
	     34▕ }
	     35▕

**Comment by allanlaal** [comment]
in my example, the fix would be:

`$this->app?->auth->guard($driver)->setUser($user);`

**Comment by driesvints** [comment]
No plans for this sorry. Most likely you're using this incorrectly. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
