### ISSUE TITLE
Losing access to extended testing tools

### ISSUE THREAD

**Issue by tommica** [laravel/browser-kit-testing#26]
When using

    use Laravel\BrowserKitTesting\TestCase as BaseTestCase;

over

    use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

we lose the ability to use things like "assertDatabaseHas":

    Error: Call to undefined method Tests\Unit\UserTest::assertDatabaseHas()

**Comment by tommica** [comment]
Ah, seems that instead of "assertDatabaseHas" I need to use "seeInDatabase"

**Comment by kmbt** [comment]
Stumbling upon this issue (via google) when having the same problem saved me time. Thanks :) :+1:
