### ISSUE TITLE
Checkbox testing

### ISSUE THREAD

**Issue by Shuyinsama** [laravel/browser-kit-testing#39]
I have a couple of forms where there are checkboxes that are required.

The input fields get the following attribute `name="permissions[]"`
But I can't seem to check these checkboxes through testing, I keep getting the following error:

`InvalidArgumentException: Cannot set value on a compound field "permissions".`

Do I need to specify a index in the name attribute?

**Comment by nafiesl** [comment]
You might want to use it like this:

```php
        $this->submitForm(trans('user.create'), [
            'name' => 'Nama User',
            'username' => 'user_name',
            'email' => 'user@mail.com',
            'password' => 'password',
            'password_confirmation' => 'password',
            'role' => [1,2],
        ]);
```
Note that the **role** field is an array field.

From this [source](https://github.com/nafiesl/Laravel-Starter-Kit/blob/94200464d7ed7e83d1ea7aafffb62aa24d5a64f0/tests/ManageUsersTest.php#L22-L29)

Which tests a **user creation** feature on this [view](https://github.com/nafiesl/Laravel-Starter-Kit/blob/94200464d7ed7e83d1ea7aafffb62aa24d5a64f0/resources/views/users/create.blade.php#L9-L35)

**Comment by Shuyinsama** [comment]
Yes that seems to work indeed.

Now I have encountered a different problem. I am trying to test the creation of a user. I have seeded the database with 3 roles by default (administrator, executive and user) during test though the code gives me the following error:

`InvalidArgumentException: Input "roles[]" cannot take "executive" as a value (possible values: administrator).`

It seems like the code does not see the other roles, even though they are there both in the database and in the frontend code.

**Comment by nafiesl** [comment]
You might need to check the seeded roles record and checkboxes on view before submitting the form.

```php

    $this->visit('users/create');

    // check the seeded data exists on database
    dump(\DB::table('your_roles_table_name')->get());

    // Check that existing roles has properly
    // passed to the view on checkboxes
    $this->dump();

    $this->submitForm('Create user', [
        // ...fields with values....
    ]);

```
Just to make sure the seeded roles has been properly passed to the view.

**Comment by Shuyinsama** [comment]
Thanks for helping!

This is the return of the dump

```sh
Illuminate\Support\Collection {#17792
  #items: array:3 [
    0 => {#17794
      +"id": "1"
      +"name": "administrator"
      +"guard_name": "web"
      +"created_at": "2017-11-10 06:17:36"
      +"updated_at": "2017-11-10 06:17:36"
    }
    1 => {#17795
      +"id": "2"
      +"name": "executive"
      +"guard_name": "web"
      +"created_at": "2017-11-10 06:17:36"
      +"updated_at": "2017-11-10 06:17:36"
    }
    2 => {#17796
      +"id": "3"
      +"name": "user"
      +"guard_name": "web"
      +"created_at": "2017-11-10 06:17:36"
      +"updated_at": "2017-11-10 06:17:36"
    }
  ]
}
```

But then the `$this->dump()` gives me an error:

```sh
1) UserFormTest::testCreateUserConfirmedForm
Error: Call to a member function getContent() on null
```

Here is the test in question:

```php
public function testCreateUserConfirmedForm()
    {
        // Make sure our events are fired
        Event::fake();

        // Create any needed resources
        $faker = Faker\Factory::create();
        $firstName = $faker->firstName;
        $lastName = $faker->lastName;
        $email = $faker->safeEmail;
        $password = $faker->password(8);

        // check the seeded data exists on database
        dump(\DB::table(config('permission.table_names.roles'))->get());

        // Check that existing roles has properly
        // passed to the view on checkboxes
        $this->dump();

        $this->actingAs($this->admin)
             ->visit('/admin/auth/user/create')
             ->submitForm('Create', [
                'first_name' => $firstName,
                'last_name' => $lastName,
                'email' => $email,
                'password' => $password,
                'password_confirmation' => $password,
                'active' => '1',
                'confirmed' => '1',
                'confirmation_email' => '1',
                'roles' => ['executive', 'user'],
             ])
             ->seePageIs('/admin/auth/user')
             ->see('The user was successfully created.')
             ->seeInDatabase(config('access.table_names.users'),
                 [
                     'first_name' => $firstName,
                     'last_name' => $lastName,
                     'email' => $email,
                     'active' => 1,
                     'confirmed' => 1,
                 ])
             ->seeInDatabase(config('permission.table_names.model_has_roles'), ['model_id' => 4, 'role_id' => 2])
             ->seeInDatabase(config('permission.table_names.model_has_roles'), ['model_id' => 4, 'role_id' => 3]);

        Event::assertDispatched(UserCreated::class);
    }
```

**Comment by nafiesl** [comment]
The `$this->dump();` should be after you visit the page and before submit the form.

Try this:

```php
$this->actingAs($this->admin)
     ->visit('/admin/auth/user/create');

$this->dump();

$this->submitForm('Create', [
    'first_name' => $firstName,
    'last_name' => $lastName,
    'email' => $email,
    'password' => $password,
    'password_confirmation' => $password,
    'active' => '1',
    'confirmed' => '1',
    'confirmation_email' => '1',
    'roles' => ['executive', 'user'],
]);
```

This just to confirm that your html page renders the checkbox based on seeded roles.

**Comment by Shuyinsama** [comment]
Yeah sorry, I got that working. The outputed data is the full HTML of the page and I can see the checkboxes in there with the correct values.

The weird thing is that when I do `Artisan::call('db:seed') before the `$this->actingAs()` part it seems to work fine. Which is weird since the database is correct at the given times
