### ISSUE TITLE
Missing mockery/mockery dependency in composer.json

### ISSUE THREAD

**Issue by Jalle19** [laravel/browser-kit-testing#41]
This library seems to assume that people have `mockery/mockery` defined as a project dependency. Currently I have to have it there only so that this library works. Please consider adding it as a real dependency.

https://github.com/laravel/browser-kit-testing/blob/master/src/Concerns/MocksApplicationServices.php#L5 is an example of where it is used.

**Comment by driesvints** [comment]
Sent in a PR for this.

**Comment by driesvints** [comment]
Should be fixed now.
