### ISSUE TITLE
How to test a form with bootstrap tabs?

### ISSUE THREAD

**Issue by abkiran** [laravel/browser-kit-testing#57]
Each tab has a different form with same save button.

**Comment by nafiesl** [comment]
You can use id attribute on each save button. Then on `press` on `submitForm` method, we can use the submit button `id` attribute.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
