### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by scocio** [laravel/browser-kit-testing#59]
Please forgive me if I'm overlooking a way to do this but I'm having trouble figuring out how set headers on visit/get/post etc...

My specific use case is that I'd like to send user agents to verify that android and ios specific parts of my pages are working properly.

It looks like in the Illuminate version of MakesHttpRequests that functionality is available via MakesHttpRequests::withHeader, is that something y'all might consider backporting to browser-kit-testing?

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L55-L59

Thanks!

**Comment by driesvints** [comment]
Feel free to send in a PR which implements this in a clean way.

**Comment by driesvints** [comment]
I was looking into this but realised that this isn't a real life situation. The `visit` method etc means a situation for an actual person visiting the page through a browser. People visiting urls in a browser don't tend to set their custom headers.

You can already use `get`, `post`, etc and pass headers as the second param.
