### ISSUE TITLE
Ajax request in form cannot see selection

### ISSUE THREAD

**Issue by sl5310** [laravel/browser-kit-testing#60]
If the select box's data is populate by a ajax call, unable to get options of the select box

**Comment by nafiesl** [comment]
Yes, it is. As far as i know, browserkit test package does not work with javascript alerts, text or anything dynamically generared by javascript (or ajax actions). It only works for text, form, fields, or html which generated by php.

You can use laravel dusk to test it.

**Comment by driesvints** [comment]
Heya, please use Dusk if you want to simulate a browser: https://github.com/laravel/dusk
