### ISSUE TITLE
Mulitple Browser Sessions to evaluate a scalability of a website 

### ISSUE THREAD

**Issue by ronlinet** [laravel/browser-kit-testing#74]
I would to simulate multiple simultaneous connections and form submit action on a Laravel instance to evaluate evaluate how many users can the website take.  Can this be done with this package ?

**Comment by driesvints** [comment]
Unfortunately not. What you're looking for is [Dusk](https://github.com/laravel/dusk) I believe or something like Artillery: https://artillery.io
