### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by DanielKeeble** [laravel/browser-kit-testing#8]
Am I correct in saying this depends on symfony/dom-crawler? Specifically in the InteractsWithPages trait.

**Comment by zgosalvez** [comment]
You're correct. The docs is missing important packages besides this. You'll have to add the missing dependencies (taken from Laravel 5.3 composer.json) as well.

E.g.
```json
"symfony/css-selector": "3.1.*",
"symfony/dom-crawler": "3.1.*",
"laravel/browser-kit-testing": "^1.0",
```

**Comment by acacha** [comment]
https://github.com/laravel/browser-kit-testing/pull/9
